### ISSUE TITLE
Stop tracking config/secrets.yml ?

### ISSUE THREAD

**Issue by siruguri** [akanshmurthy/railsbridge-hackathon#13]
I'm writing tests for bitly, and need to test the test with a Bitly client. I want to leave in some pieces of the code I'm writing, as a best practice example - specifically how to initialize the client with a password.

I usually check in `config/secrets.yml`, but use the `dotenv` gem - but that might be too many steps for a beginner coder. Instead, I want to stop tracking `config/secrets` and add it to `.gitignore` I can also create a `config/secrets.yml.sample` that does get checked in.

Is this strategy ok by you guys?

**Comment by siruguri** [comment]
@schaui6 @akanshmurthy

**Comment by schaui6** [comment]
@siruguri sounds good to me

**Comment by akanshmurthy** [comment]
Sounds good. I'm even leaving out the client altogether so that they can go to the API documentation and figure it out but it might be good to have one with a client so that they can understand a bit better.

**Comment by siruguri** [comment]
Thanks.

Typed on a phone
