### ISSUE TITLE
FactoryGirl vs Fixtures

### ISSUE THREAD

**Issue by siruguri** [akanshmurthy/railsbridge-hackathon#14]
In spec'ing `posts_controller`, I need to decide how to deal with post creation which expects a `current_user`

This is to support the spec'ing of the creation of a Bitly link when a post is created.

Therefore, I need to somehow have a user in the db - or change the code to not require a logged in user. The latter is easier, but I'd rather leave in that logic, and use `fixtures` to create test db records, as fixtures are a simpler concept than going through the FactoryGirl abstraction.

Any thoughts, comments?

**Comment by akanshmurthy** [comment]
You can stub a user and pass that to the post :create call or just leave out the creation when a post is created if you'd like (since the real thing we want to make sure is just that the API call is happening). Up to you. You have full power over how you want to do this :)

**Comment by siruguri** [comment]
Ha, thanks for the power... :)

I'm just curious about what you mean by "stub the user" - do you mean, mock
`current_user` to return a stubbed `User` instance?

**Comment by akanshmurthy** [comment]
Yep. Not sure if that would work for the post creation but that's worth a try if you want to go that route. Worst case you can remove the logged in user callback.
