### ISSUE TITLE
Cloudinary Input in Post Controller Spec

### ISSUE THREAD

**Issue by camachom** [akanshmurthy/railsbridge-hackathon#21]
```ruby
# post_controller_spec.rb line 126
file_io = fixture_file_upload 'files/bridgetroll.svg', 'image/svg'
```

file_io is a Tempfile which is then passed into params[:post][:image]. In this case, the Cloudinary API requires a path to a file, so no matter what students do in the post_controller, they won't be able to successfully make the API call. 

```ruby
Cloudinary::Uploader.upload(file, options = {})
```

I could easily fix this on line 127 by using (file_io.path) instead of the Tempfile itself. Also, by the recommendation of the [docs](http://ruby-doc.org/stdlib-1.9.3/libdoc/tempfile/rdoc/Tempfile.html#class-Tempfile-label-Explicit+close), Tempfiles should be explicitly garbage collected by using #unlink.

**Comment by akanshmurthy** [comment]
Awesome, good catch! CC: @schaui6 @siruguri
