### ISSUE TITLE
Create tests for Twilio API portion

### ISSUE THREAD

**Issue by akanshmurthy** [akanshmurthy/railsbridge-hackathon#4]

**Comment by schaui6** [comment]
@akanshmurthy - question, any idea if we were planning on having students create their api keys through twillio or use one of our test api keys?

**Comment by akanshmurthy** [comment]
I think they should create their own. That will help them understand the real process of signing up for an API and how to get the keys.

**Comment by siruguri** [comment]
+1

Typed on a phone
